server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test
    username: root
    password: tonpaz-diztoB-rapqi7
#    url: jdbc:mysql://sh-cynosdbmysql-grp-ograihi2.sql.tencentcdb.com:20774/prod
#    username: root
#    password: r5e5N8nK
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

we-com:
  corp-id: ww87ecff7cdc463532
  agent-id: 1000002
  corp-secret: OvBxtHNEx98vfiMWjUmudOLCg_zh-05clvmIIHTxM3Q
  redirect-uri: https://www.qhr.goldenguard.top/api/auth/wecom/callback

# 日志
logging:
  level:
    mybatis: DEBUG
    com.baomidou.mybatis plus: DEBUG

